directories:
  output: dist-release-clean
  buildResources: build
appId: com.edgeset.app
productName: EdgeSet Tennis
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  installerLanguages:
    - English
    - Spanish
    - Portuguese
    - German
    - Italian
    - French
    - SimpChinese
    - Japanese
    - Arabic
    - Korean
    - Russian
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
electronVersion: 40.0.0
