import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { TrendingUp, DollarSign, Activity, PieChart, ShieldCheck } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';

export default function PerformancePage() {
    const [metrics, setMetrics] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadData();
    }, []);

    async function loadData() {
        setLoading(true);
        const data = await api.getPerformanceSummary();
        setMetrics(data || {
            roi: 0, yield: 0, total_profit: 0, total_bets: 0, win_rate: 0, chart_data: []
        });
        setLoading(false);
    }

    if (loading) return <div className="min-h-screen bg-slate-950 flex items-center justify-center text-emerald-500 animate-pulse">Auditing Performance Ledger...</div>;

    const isPositive = metrics.total_profit >= 0;

    return (
        <div className="min-h-screen bg-slate-950 text-white p-8">
            <header className="mb-12 text-center">
                <div className="inline-flex items-center gap-2 px-4 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-xs font-bold uppercase tracking-widest mb-4">
                    <ShieldCheck size={14} /> Verified Track Record
                </div>
                <h1 className="text-4xl font-black tracking-tight mb-2">System Performance</h1>
                <p className="text-slate-400 max-w-2xl mx-auto">
                    Transparency is our core value. This page displays the raw, immutable results of every recommendation generated by our Value Engine.
                </p>
            </header>

            <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-6 mb-12">
                <KPICard
                    label="Total Profit"
                    value={`${isPositive ? '+' : ''}$${metrics.total_profit}`}
                    sub="Based on $100 units"
                    icon={<DollarSign />}
                    trend={isPositive ? 'up' : 'down'}
                />
                <KPICard
                    label="ROI / Yield"
                    value={`${metrics.roi}%`}
                    sub="Return on Investment"
                    icon={<TrendingUp />}
                    trend={metrics.roi > 0 ? 'up' : 'down'}
                />
                <KPICard
                    label="Win Rate"
                    value={`${metrics.win_rate}%`}
                    sub={`${metrics.total_bets} Total Bets`}
                    icon={<PieChart />}
                    color="blue"
                />
                <KPICard
                    label="Active Model"
                    value="v2.1"
                    sub="XGBoost Calibration"
                    icon={<Activity />}
                    color="purple"
                />
            </div>

            {/* Equity Curve */}
            <div className="max-w-6xl mx-auto bg-slate-900/50 border border-slate-800 rounded-3xl p-8 mb-12">
                <div className="flex justify-between items-center mb-8">
                    <h3 className="text-xl font-bold">Equity Curve (Cumulative Profit)</h3>
                    <select className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-1 text-sm text-slate-300">
                        <option>All Time</option>
                        <option>Last 30 Days</option>
                    </select>
                </div>

                <div className="h-[400px] w-full">
                    {metrics.chart_data.length > 0 ? (
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={metrics.chart_data}>
                                <defs>
                                    <linearGradient id="colorProfit" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#10b981" stopOpacity={0.3} />
                                        <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                                <XAxis
                                    dataKey="date"
                                    stroke="#475569"
                                    tickFormatter={(str) => new Date(str).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                                />
                                <YAxis stroke="#475569" />
                                <Tooltip
                                    contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #1e293b', borderRadius: '8px' }}
                                    formatter={(value: any) => [`$${value}`, 'Profit']}
                                />
                                <Area
                                    type="monotone"
                                    dataKey="cumulative_profit"
                                    stroke="#10b981"
                                    strokeWidth={3}
                                    fillOpacity={1}
                                    fill="url(#colorProfit)"
                                />
                            </AreaChart>
                        </ResponsiveContainer>
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-slate-500">
                            <Activity size={48} className="mb-4 opacity-50" />
                            <p>No settled bets in the ledger yet.</p>
                            <p className="text-sm">Wait for match results to populate history.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

function KPICard({ label, value, sub, icon, trend, color = 'emerald' }: any) {
    const colors: any = {
        emerald: "text-emerald-400 bg-emerald-500/10",
        blue: "text-blue-400 bg-blue-500/10",
        purple: "text-purple-400 bg-purple-500/10",
        red: "text-red-400 bg-red-500/10",
    };

    const finalColor = trend === 'down' ? 'red' : color;

    return (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 flex items-start justify-between hover:border-slate-700 transition-colors">
            <div>
                <div className="text-slate-400 font-medium text-sm mb-1">{label}</div>
                <div className="text-3xl font-black text-white mb-1">{value}</div>
                <div className="text-slate-500 text-xs font-bold">{sub}</div>
            </div>
            <div className={`p-3 rounded-xl ${colors[finalColor]}`}>
                {icon}
            </div>
        </div>
    )
}
